name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # هنا نخبر خادم GitHub أن يرسل الكود مباشرة إلى حسابك ezzitia على Hugging Face
        run: git push --force https://ezzitia:$HF_TOKEN@huggingface.co/spaces/ezzitia/simple-devops-project main